### ISSUE TITLE
Add musdb.jl to dataset description

### ISSUE THREAD

**Issue by faroit** [davidavdav/Musdb.jl#1]
Hi, 

I just found your julia based parser. 👏 This is really awesome. Thanks a lot. I will try it out soon.
Do you think it is stable enough so that I can add it to the list of tools for the database description page?

**Comment by davidavdav** [comment]
You mean like in the description of musdb itself or the signal separation challenge? 

Sure.  It probably needs some testing by others than me, but the code itself should be OK.

**Comment by faroit** [comment]
I think for now I would just add it the [musdb description page](https://sigsep.github.io/musdb). I will test it at the weekend and leave this issue open till then.

One more thing: did you have have a look at our [evaluation tools](https://github.com/sigsep/sigsep-mus-eval)? We are really unhappy with the performance. Maybe Julia could come to a rescue here. Would be interesting to know if you can estimate if a reimplementation in julia would be difficult or not (see core code [here](https://github.com/sigsep/sigsep-mus-eval/blob/master/museval/metrics.py).

**Comment by davidavdav** [comment]
Ehm yes, I did have a look at the evaluation tools description but did not install and/or operate them.  If performance is an issue, I suppose you're looking at and alternative to `bss_eval()`?

I can't immediately appreciate from the python code what the computationally hardest operation is, and if this could potentially be improved by recoding in Julia.  I suppose I'd have to study the articles referenced.  In general, if you have to do broadcasting-like inner loops yourself, recoding in Julia could improve performance a lot.  But if most computations happen inside numpy, I don't think there is much to gain.

**Comment by faroit** [comment]
hey. we've updated the [dataset page](https://sigsep.github.io/datasets/musdb.html) and included the link to this project. Thanks again.

Concerning the evaluation, we are still evaluating what to do next as the current metrics are a bit outdated anyway, so we don't want to invest further time in optimizing it.
